#Application Configuration TestIngresoEvertec 
server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false

  security:
    user:
      name: admin
      password: 1234

  # ===============================
  # HEROKU DB
  # ===============================
  datasource:
    username: postgres
    password: Medellin123+-*
    url: jdbc:postgresql://localhost:5432/devcoDb

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    level: org.springframework.web=DEBUG
